name: Java CI with Maven and PostgreSQL

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: carport
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Install dependencies
        run: mvn install -DskipTests

      - name: Wait for PostgreSQL to be ready
        run: sleep 15  # Wait for 15 seconds to ensure PostgreSQL is ready

      - name: Run tests
        env:
          DEPLOYED: true  # Signals your application to use the deployed environment
          JDBC_USER: postgres
          JDBC_PASSWORD: postgres
          JDBC_CONNECTION_STRING: jdbc:postgresql://localhost:5432/carport?currentSchema=public
          JDBC_DB: carport
        run: mvn test
